### PR TITLE
Composer Autoloading & Class Name

### PR DESCRIPTION
**Pull request by ericdowell**
## What this did
Sturdy case markroland when referencing the namespace (e.g. `MarkRoland`).

The composer.json file sets the src folder to be namespaced as `MarkRoland\Emma`, but the Emma (Client) class only referenced MarkRoland (`markroland`).
The Emma (Client) class should be under the same namespace as in the composer.json, this is now so.

Renamed the Emma class to Client, making the reference to the class less redundant (otherwise `MarkRoland\Emma\Emma`) and more descriptive (`MarkRoland\Emma\Client`).

Updating tests, autoload-dev the tests and namespace them under `MarkRoland\Emma\Tests` and adding phpunit ~4.8 under require-dev in composer.json.
Updating travis to use `vendor/bin/phpunit` for running unit tests. Updating bootstrap to use autoload.php instead of the Emma (Client) class directly.

Updating all php files in examples folder to reference the Emma (Client) class correctly and use the autoload.php file.

Removing all closing php tags ?> in all files, this has become optional and is not recommended.

Updating the readme file with reference to new class name `Client` and adding note about the examples folder.

**Issue:** https://github.com/markroland/emma/issues/5

### CODE REVIEW

**Comment by markroland** [comment]
Thank you for your contributions. Based on my current work load it will take me about 1-2 weeks to get this reviewed and merged. Thanks!

**Comment by ericdowell** [comment]
If reviewed and approved, might need to tag these changes as 3.0 since `composer require markroland/emma:~2` covers versions `2.*`.

**Comment by ericdowell** [comment]
Adding `@deprecated` to trigger methods as Emma has stated on their website: http://api.myemma.com/api/external/triggers.html

**Comment by markroland** [comment]
Thanks for these updates. Since a number of things have changed, I think a version increase would make sense. My business has actually stopped using Emma since I first wrote this so I'm no longer actively using that, that's why it's taking me some time to dive back into it. Thanks for your patience.

**Comment by markroland** [comment]
Eric, I'm very sorry for the delay on this. I just can't seem to find the time to fire it up and run the tests. I'm going to go ahead and trust that it's all good and do the merge.

**Pull request merged**
